# Generated by Django 5.0.2 on 2024-04-17 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userdodoupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DodoApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_dead_approval', models.BooleanField(default=False)),
                ('dodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.dodo')),
            ],
        ),
    ]
